name: Build Nginx Portable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本作为 Runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          # 在 Ubuntu 上安装依赖
          sudo apt-get update
          sudo apt-get install perl git curl unzip build-essential libpcre3-dev libssl-dev -y

      - name: Get latest Nginx version
        id: get_version
        run: |
          # 使用 curl 获取 nginx 官方页面
          web=$(curl -s https://nginx.org/en/download.html)
          # 提取所有版本号，并选取最新的版本
          VERSION=$(echo "$web" | grep -oP 'nginx-\d+\.\d+\.\d+\.tar.gz' | sort -V | tail -n 1 | sed 's/nginx-\(.*\)\.tar.gz/\1/')
          echo "Latest Nginx version: $VERSION"
          echo "::set-output name=version::$VERSION"  # 设置输出变量

      - name: Install Nginx Portable
        run: |
          # 直接在仓库的根目录下执行编译
          bash compile ${{ steps.get_version.outputs.version }}

      - name: Upload Nginx to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/nginx-${{ steps.get_version.outputs.version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
